# Generated by Django 4.1.7 on 2023-03-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_payment_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplace',
            name='payment',
        ),
    ]
